// Package strm builds and verifies the stable, signed stream URLs written to
// mountless media libraries.
package strm

import (
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net"
	"net/url"
	"path"
	"path/filepath"
	"strings"

	"github.com/sirrobot01/decypharr/internal/config"
	"github.com/sirrobot01/decypharr/internal/utils"
)

const streamVersion = "v1"

func key(secret string) ([]byte, error) {
	decoded, err := hex.DecodeString(secret)
	if err != nil || len(decoded) != sha256.Size {
		return nil, fmt.Errorf("invalid STRM signing secret")
	}
	return decoded, nil
}

// Sign returns a domain-separated HMAC for an entry/file identity.
func Sign(secret, purpose string, parts ...string) (string, error) {
	signingKey, err := key(secret)
	if err != nil {
		return "", err
	}
	mac := hmac.New(sha256.New, signingKey)
	_, _ = mac.Write([]byte("decypharr-strm\x00" + streamVersion + "\x00" + purpose))
	for _, part := range parts {
		_, _ = mac.Write([]byte{0})
		_, _ = mac.Write([]byte(part))
	}
	return hex.EncodeToString(mac.Sum(nil)), nil
}

func Verify(secret, purpose, signature string, parts ...string) bool {
	want, err := Sign(secret, purpose, parts...)
	if err != nil {
		return false
	}
	wantBytes, err := hex.DecodeString(want)
	if err != nil {
		return false
	}
	gotBytes, err := hex.DecodeString(signature)
	return err == nil && hmac.Equal(wantBytes, gotBytes)
}

// BaseURL returns the externally reachable application base. AppURL is
// preferred; otherwise the configured listener is used for same-host players.
func BaseURL(cfg *config.Config) (*url.URL, error) {
	if cfg == nil {
		return nil, fmt.Errorf("configuration is unavailable")
	}
	raw := strings.TrimSpace(cfg.AppURL)
	if raw == "" {
		host := strings.TrimSpace(cfg.BindAddress)
		switch host {
		case "", "0.0.0.0", "::", "[::]":
			host = "127.0.0.1"
		}
		raw = "http://" + net.JoinHostPort(strings.Trim(host, "[]"), cfg.Port)
	}
	u, err := url.Parse(raw)
	if err != nil || (u.Scheme != "http" && u.Scheme != "https") || u.Host == "" {
		return nil, fmt.Errorf("application URL must be an absolute HTTP or HTTPS URL")
	}
	if u.User != nil || u.RawQuery != "" || u.Fragment != "" {
		return nil, fmt.Errorf("application URL cannot contain credentials, a query, or a fragment")
	}
	basePath := strings.Trim(cfg.URLBase, "/")
	if basePath != "" {
		currentPath := strings.Trim(u.Path, "/")
		if currentPath != basePath && !strings.HasSuffix(currentPath, "/"+basePath) {
			u.Path = path.Join(u.Path, basePath)
		}
	}
	u.RawPath = ""
	u.RawQuery = ""
	u.Fragment = ""
	return u, nil
}

func FileURL(base *url.URL, secret, infohash, fileID, displayName string) (string, error) {
	if base == nil || infohash == "" || fileID == "" {
		return "", fmt.Errorf("STRM base URL, entry identity, and file identity are required")
	}
	signature, err := Sign(secret, "stream", infohash, fileID)
	if err != nil {
		return "", err
	}
	u := *base
	name := filepath.Base(strings.ReplaceAll(displayName, "\\", "/"))
	if name == "." || name == ".." || name == "/" || name == "" {
		name = "media"
	}
	if strings.ContainsAny(infohash, "/\\") || strings.ContainsAny(fileID, "/\\") {
		return "", fmt.Errorf("STRM identities cannot contain path separators")
	}
	u.Path = path.Join(u.Path, "stream", streamVersion,
		infohash, fileID, name)
	u.RawPath = ""
	query := u.Query()
	query.Set("s", signature)
	u.RawQuery = query.Encode()
	return u.String(), nil
}

// ParseOwnedURL recognizes and authenticates one URL generated by FileURL.
func ParseOwnedURL(raw, secret string) (infohash, fileID string, ok bool) {
	u, err := url.Parse(strings.TrimSpace(raw))
	if err != nil || (u.Scheme != "http" && u.Scheme != "https") {
		return "", "", false
	}
	segments := strings.Split(strings.Trim(u.EscapedPath(), "/"), "/")
	for i := 0; i+4 < len(segments); i++ {
		if segments[i] != "stream" || segments[i+1] != streamVersion {
			continue
		}
		entryID, entryErr := url.PathUnescape(segments[i+2])
		stableID, fileErr := url.PathUnescape(segments[i+3])
		if entryErr != nil || fileErr != nil || entryID == "" || stableID == "" {
			return "", "", false
		}
		if Verify(secret, "stream", u.Query().Get("s"), entryID, stableID) {
			return entryID, stableID, true
		}
		return "", "", false
	}
	return "", "", false
}

func FileName(mediaName string, keepExtension bool) string {
	if keepExtension {
		return mediaName + ".strm"
	}
	return utils.RemoveExtension(mediaName) + ".strm"
}
